### PR TITLE
Create modified-SignalQualityIndex.py

### PR DESCRIPTION
**Pull request by hejs9603**
fir_fillter() - signal - np.array [1*N] 

fir_fillter(), len(signal) will be equal to 1, and the fir_filter doesn't work

so we need change "len(signal)" to "len(signal[0])", we get the N

### CODE REVIEW

**Comment by hejs9603** [comment]
fir_fillter() - signal - np.array [N*1]

so would you like to provide some example data

**Comment by kdarti** [comment]
Hi @hejs9603. I had a look at the code you provided:

```python
if __name__ == "__main__":
    a = np.random.random([1,500])
    b = a+np.random.random([1,500])
    c = np.random.random([1,500])
    d = c+np.random.random([1,500])

    e = SQI(a, b, c, d, 50)
    print(e)
```
a,b,c,d are two-dimensional arrays in this case (1,500) and as as you say, if you take e.g. len(a) it'll return 1, whereas you actually want 500. I'd suggest using a 1d array instead e.g. a = np.random.random([500]) and it'll work fine.

If you want to try SQI on real fNIRS data you can use these datasets: https://github.com/Artinis-Medical-Systems-B-V/snirf_data_example 

If you want to use python, there is https://pypi.org/project/pysnirf2/ for reading snirf files. 

Also remember that you have write your own code for segmenting the data into the segment size you want to look at since the SQI funciton only returns a single value for the whole timeseries.

**Comment by Horschig** [comment]
Feel free to continue posting here. I closed this, because there is no code change in our repository needed.

**Comment by hejs9603** [comment]
Thanks for your reply! A very practical suggestion!

Can you advise on the length of  segement time? 10 seconds, 1 second or the entire data can be used. 
Or if there are any literatures?

**Comment by kdarti** [comment]
10 seconds is the recommended segment length.

**Pull request closed without merging**
